name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Hardhat lint
        run: yarn hardhat:lint --max-warnings=0

      - name: Hardhat tests
        run: yarn workspace @se-2/hardhat test

      - name: Next.js lint
        run: yarn next:lint --max-warnings=0

      - name: Next.js type-check
        run: yarn next:check-types

      - name: Next.js unit tests
        run: yarn workspace @se-2/nextjs vitest run

      - name: Next.js build
        run: yarn next:build
        env:
          NEXT_PUBLIC_IGNORE_BUILD_ERROR: "false"
